window.VA = window.VA || {};

VA.races = {
  human:    {name:'Люди', icon:'👤', tag:'neu', karma:'нейтральная', bonus:null,
             desc:'Универсальная раса без бонусов и штрафов.',
             traits:['Универсальность','Приспособляемость'], growthBonus:0},
  elf:      {name:'Эльфы', icon:'🧝', tag:'pos', karma:'положительная', bonus:'nature',
             desc:'Древняя раса, связанная с природой.',
             traits:['Талант к магии природы','Живучесть','Гордыня'], growthBonus:0},
  dwarf:    {name:'Гномы', icon:'⛏️', tag:'neu', karma:'нейтральная', bonus:'industry',
             desc:'Упорные мастера подземелий.',
             traits:['Мастер металлургии','Живучесть','Посредственные в магии'], growthBonus:0},
  orc:      {name:'Орки', icon:'🪓', tag:'neg', karma:'отрицательная', bonus:'melee',
             desc:'Воинственная раса.',
             traits:['Физическая сила','Высокая плодовитость','Гордыня'], growthBonus:0.0005},
  undead:   {name:'Нежить', icon:'💀', tag:'neg', karma:'отрицательная', bonus:'alchemy',
             desc:'Восставшие мертвецы.',
             traits:['Размножаются искусственно','Неистовая вера','Живучесть'],
             growthBonus:0, artificial:true},
  dragon:   {name:'Драконы', icon:'🐉', tag:'neu', karma:'нейтральная', bonus:'artifact',
             desc:'Могучие создания.',
             traits:['Мастер артефакторики','Физическая сила','Малочисленность','Гордыня'],
             growthBonus:-0.0005},
  halfling: {name:'Полурослики', icon:'🍺', tag:'pos', karma:'положительная', bonus:'food',
             desc:'Небольшой, но предприимчивый народ.',
             traits:['Талант к сельскому хозяйству','Ловкость','Высокая плодовитость'],
             growthBonus:0.0005},
  demon:    {name:'Демоны', icon:'😈', tag:'neg', karma:'отрицательная', bonus:'demonology',
             desc:'Порождения хаоса.',
             traits:['Мастер демонологии','Физическая сила','Паранойя'], growthBonus:0},
  angel:    {name:'Ангелы', icon:'👼', tag:'pos', karma:'положительная', bonus:'culture',
             desc:'Небесные посланники.',
             traits:['Неистовая вера','Живучесть','Гордыня','Малочисленность'], growthBonus:-0.0005},
  mech:     {name:'Механоиды', icon:'⚙️', tag:'neu', karma:'нейтральная', bonus:'engineering',
             desc:'Созданные для труда.',
             traits:['Размножаются искусственно','Мастер инженерии','Живучесть'],
             growthBonus:0, artificial:true},
  beast:    {name:'Зверолюди', icon:'🐺', tag:'neu', karma:'нейтральная', bonus:'animal',
             desc:'Полулюди-полузвери.',
             traits:['Физическая сила','Скорость','Талант к животноводству'], growthBonus:0},
  crystal:  {name:'Кристаллиды', icon:'💎', tag:'neu', karma:'нейтральная', bonus:'crystal',
             desc:'Живые кристаллы.',
             traits:['Мастер кристаллургии','Регенерация','Малочисленность'], growthBonus:-0.0005},
  shadow:   {name:'Теневые', icon:'🌑', tag:'neg', karma:'отрицательная', bonus:'stealth',
             desc:'Обитатели тьмы.',
             traits:['Талант к маскировке','Скорость','Паранойя'], growthBonus:0},
  leviathan:{name:'Левиафаны', icon:'🌊', tag:'neu', karma:'нейтральная', bonus:'sea',
             desc:'Повелители морей.',
             traits:['Мастер мореходства','Живучесть','Малочисленность'], growthBonus:-0.0005}
};